### PR TITLE
Add a WebSocketContainerListener. Initial usage is to configure TLS

### PR DESCRIPTION
**Pull request by markt-asf**
If this approach is acceptable then I can add some suitable words to the specification document..

### CODE REVIEW

**Comment by joakime** [comment]
I'm seeing how complicated this would be to implement on the Jetty side.

**Comment by markt-asf** [comment]
ACK. The wording may need some adjustment but the idea is that `getSSLContextForClientConnection()` is called before a new network connection is established.
For example, it we could change it to only being called when the protocol is `wss` and then returning a `null` `SSLContext` would trigger a connection failure.

**Comment by markt-asf** [comment]
So, is this being added for 2.1 or do we want to push it back to the next iteration?

**Comment by joakime** [comment]
What's your feeling about it?
I'm not sure anymore what's better.

**Comment by markt-asf** [comment]
I'm confident that `SSLContext` is the mechanism to use to pass the configuration to WebSocket.

I'm currently on the fence as to whether this approach or the original is better.

For this approach the container would:
- if the connection URI uses wss, iterate through the configured listeners calling `getSSLContextForClientConnection()`
- if there is an existing connection to the same server with the same SSSLContext and the transport supports multiplex, re-use the connection, else create a new connection with the given SSLContext

For #372 the container would:
- if the connection URI uses wss, get the SSLContext
- if there is an existing connection to the same server with the same SSLContext and the transport supports multiplex, re-use the connection, else create a new connection with the given SSLContext

(I've skipped all the validation etc in the above)

Tomcat currently uses the #372 approach (minus the multiplex checks)

Having written this up, my main concern with this approach is specifying the behaviour with multiple listeners with potentially inconsistent results. I think the #372 is simpler in that regard.

WDYT?

**Comment by markt-asf** [comment]
Ping @joakime
Any thoughts on the above? I'm leaning towards the #372 based approach described above.

**Comment by markt-asf** [comment]
Absent any other feedback, I am going to proceed with the #372 based approach described above. I'll close this PR once I have a new PR prepared.

**Comment by markt-asf** [comment]
Withdrawn in favour of #388

**Pull request closed without merging**
