### PR TITLE
Fix #179: Avoid double wrapping with Collections.unmodifiableList()

### LINKED ISSUE #179: Double wrapping of Collections.unmodifiableList in ClientEndpointConfig.Builder
Minor performance improvement in the implementation of ClientEndpointConfig.Builder. It wraps all the lists into Collections.unmodifiableList and then again in DefaultClientEndpointConfig. Moreover, the empty lists themselves are unmodifiable. The same improvement can be done for ServerEndpointConfig.Builder.

Will attach the patch for ClientEndpointConfig.Builder to the issue mail.

### PR DESCRIPTION
**Pull request by markt-asf**
Fix #179 by removing wrapping in call to Default[Client|Server]EndpointConfig constructor

### CODE REVIEW

**Comment by markt-asf** [comment]
It isn't that simple. There are multiple things to take account of here:

- Oracle is not the copyright holder for my changes - I am (The ECA does not include copyright assignment).
- Eclipse is (probably) the copyright holder for collective work that consists of the original donation + Eclipse committer changes.
- I don't know if the donation from Oracle to Eclipse included a copyright assignment.
- There may be other factors I'm not aware of.

I note that jaxrs-api is making changes without any modifications to the copyright headers.

There needs to be a common approach to handling this across Jakarta EE. This feels like a question for the PMC. I'll start a discussion there.

**Comment by markt-asf** [comment]
Excellent. Thanks for that reference. That answers all the questions I had. I'll update the PR.

**Comment by markt-asf** [comment]
Done.

**Comment by markt-asf** [comment]
Eclipse IP policy says such a block is optional. I'm -1 for adding it. I don't want my name in the source file.
In addition, data like that is hard to maintain correctly and, ultimately, the version control tools do a much better job of providing it.

**Comment by m0mus** [comment]
@markt-asf not agree. It gives you a quick overview of what was done and who's done it. Sometimes history is not retained. This project is a good sample.

**Comment by joakime** [comment]
ping @waynebeaton or @mmilinkov 
what's the official word on this?

**Comment by m0mus** [comment]
@joakime @markt-asf As I said that I don't want to make it a blocking issue. I am approving this merge request. But I don't want you to ignore what I said about the history. This project lost the whole history when it was transferred to the Eclipse Foundation. We use Contributors section in EclipseLink and it works well.

**Pull request merged**
