### PR TITLE
Adding SpecLicense.html to javadoc classified artifacts to EE4J_8

### PR DESCRIPTION
**Pull request by joakime**
+ Adding maven-javadoc-plugin configuration for:
  * description
  * doc title
  * window title
  * header
  * bottom (with links to mailing list and included EFSL license)

Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

**Comment by joakime** [comment]
Note: I've opened Issue #306 about the missing `<organization>` and resulting bad Copyright line in the javadoc footer.
This PR is likely bad until that issue is answered / resolved.

**Comment by m0mus** [comment]
See my comments on #304

**Comment by joakime** [comment]
> I take it that we are using the EE4J_8 branch for the Jakarta EE 8 release. I'm fine with that. I think it makes sense. I just didn't realise that was what we were doing.

Technically, releases are made from Release branches. (see https://github.com/eclipse-ee4j/websocket-api/issues/295#issuecomment-516711060 )
But I think the release process that the Jenkins CI uses will create that Release branch itself.
From what starting branch?  I really don't know (yet)

**Comment by joakime** [comment]
@markt-asf @m0mus This PR has been updated with commit abfd6b83bf905270e8c0ca9f3e85e8f4dbcbc3ed

**Pull request merged**
