### PR TITLE
Fix #382 - clarify session idle timeout

### LINKED ISSUE #382: Session idle timeout doesn't define behaviour for 0 or negative values
A need for this clarification was identified in the discussions around #356 / #377. When those were closed as WONTFIX, this issue was created for this specific clarification.

The clarification is that a zero or negative value disables the timeout.

### PR DESCRIPTION
**Pull request by markt-asf**

### CODE REVIEW

**Comment by joakime** [comment]
Should probably also add similar language to ...

* RemoteEndpoint.getSendTimeout()
* WebSocketContainer.getDefaultAsyncSendTimeout()
* WebSocketContainer.setAsyncSendTimeout(long)
* WebSocketContainer.getMaxSessionIdleTimeout()
* WebSocketContainer.setDefaultMaxSessionIdleTimeout(long)

**Comment by markt-asf** [comment]
Will do.

**Comment by markt-asf** [comment]
As requested. The wording for those was technically correct but I think "zero or negative" is better than "non-positive".

**Review by jansupol — APPROVED** [review]
Looks good. I'd update the copyright year, too.

**Comment by markt-asf** [comment]
Thanks for the reminder about copyrights. Fixed.

**Review by joakime — APPROVED** [review]

**Pull request merged**
