### PR TITLE
Fix issue-211 - Add method for use by front controller

### PR DESCRIPTION
**Pull request by markt-asf**

### CODE REVIEW

**Comment by joakime** [comment]
Wow. really?
This seems awkward to me.
And the reasons laid out in issue #211 were never a problem for libraries outside of spring and sockjs. (cometd for example was able to accomplish the end goals laid out in issue #211 without the need for this API)

**Comment by joakime** [comment]
There needs to be some restrictions in place to protect previously registered `ServerEndpointConfig`.

Using this API cannot replace a previously registered `ServerEndpointConfig` path in the `ServerContainer` (either from annotations, or direct `Container.addEndpoint()` usage)

**Comment by markt-asf** [comment]
Agreed. This API isn't meant to trigger a registration. I think of it more like the equivalent of a dispatch to a WebSocket endpoint. I can clarify the language around that.

**Comment by joakime** [comment]
Don't we have text saying `ServerContainer.addEndpoint()` can only be called during Servlet initialization phase?
If so, we should probably relax that rule as well.

**Comment by markt-asf** [comment]
I've tried to clarify the language on upgrade. I've also removed the "deployment only during initialisation" restriction. I think I have updated the spec everywhere required.

**Pull request merged**
